version: '3.7'

services:
  jupyter-pyspark:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - minio

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9009:9000"
      - "9010:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data:

